id: PA4D3B0D3
initial_creation_type: input
source_metadata:
  title: Atiśa Dīpaṃkara Series
  language: bo
  description: Atiśa Dīpaṃkara Śrījñāna (982–1054), known as Jowo Jé Palden Atisha
    (jo bo rje dpal ldan a ti sha) in Tibetan, was a great Indian master and scholar.
    He spent the last ten years of his life in Tibet, teaching and translating texts,
    and was instrumental in reinvigorating Buddhism there after a period of persecution
    and decline.
  volume:
    2c1b00f05a954eada49b5bcce8e40251:
      title: Heart Treasure for the Warriors Who Long for Liberation
      parent: Advice
    28d91ad66a564caba24271b89b893664:
      title: The Lamp for the Path to Enlightenment
      parent: Advice
    ac47d0e966f04c46b32a3af35f73dfea:
      title: 'Bestower of Supreme Blessings: Guru Yoga of the Great Incomparable Lord
        Atiśa'
      parent: Guru Yoga
    74a275bfa17f434fa5a72a11bbfd3a4e:
      title: The Bodhisattva’s Garland of Jewels
      parent: Mind Training
    df1069a9f97148628e65fbc2efe8d215:
      title: An Extremely Concise Praise of the Twenty-One Tārās
      parent: Praise
    0f2a7c62513549609249383cf7cfa643:
      title: Light Offering Prayer
      parent: Prayers
    92e523a0f3d941bb98daffcb5b9f3228:
      title: Prayer for the Future of the Dharma
      parent: Prayers
    93993663bfa64010a234d143513e1f60:
      title: Prayer to Ārya Tārā
      parent: Prayers
    1609c68f140847aeace0a6539dc1233a:
      title: Short Prayer to Atiśa
      parent: Prayers
created_at: '2022-03-01T02:10:55.974948'
last_modified_at: '2022-03-01T02:10:55.974951'
statistics:
  total_words: 6190
  total_non_words: 565
quality:
  non_words_ratio: 0.09
